### ISSUE TITLE
PariDisp

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/ifelse#1]
Creare un programma paridisp.py che chieda
all'utente di inserire un numero intero
e quindi dica se e' pari o dispari

**Comment by Raffaelefrn** [comment]
Ho provato in svariati modi, se metto che il numero è uguale a 10 o ad un
qualsiasi numero funziona, ma se inserisco da tastiera il numero mi da il
seguente errore e  non so come uscirmene. Mi potete dare una mano ?

Inserisci un numero: 12
Traceback (most recent call last):
  File "pd.py", line 2, in <module>
    resto=numero%2
TypeError: not all arguments converted during string formatting

2016-03-15 21:05 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
se non carichi il codice come faccio a vedere?

**Comment by Raffaelefrn** [comment]
ho finito, ho capito dove sbagliavo, grazie lo stesso. Ora carico il
programma

2016-03-17 17:25 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma perché stai caricando in helloworld?
