### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/ifelse#2]
Scrivi un programma che calcoli il volume di un cubo o di una sfera
in base ad una scelta effettuata dall'utente.
Se l'utente sceglie di calcolare il volume di un cubo,
il programma chiedera' l'input del relativo lato,
altrimenti chiedera' il raggio della sfera.

Esempio di esecuzione:

``` bash
Calcolo del volume di un cubo o di una sfera
Effettua una scelta (1 - Cubo, 2 - Sfera)
? 1
Lato del cubo: 2
Il cubo di lato 2 ha volume 8
```

**Comment by Raffaelefrn** [comment]
Programma caricato

2016-03-15 21:06 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
rileggi il testo dell'esercizio

**Comment by Raffaelefrn** [comment]
ho riletto, cosa ho sbagliato ? invece dei numeri dovevo fare con una
stringa ?

2016-03-17 19:13 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
L'esercizio chiede di calcolare il volume di un cubo o di una sfera in base
alla scelta dell'utente

Il venerdì 18 marzo 2016, Raffaelefrn notifications@github.com ha scritto:
