### ISSUE TITLE
PrimoGrado

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/ifelse#3]
Scrivi un programma che trovi la soluzione a equazioni di primo grado
nella forma ax+b=0, con a e b interi.

Il programma dovrebbe tener conto dei casi particolari: a, b o entrambi nulli.

**Comment by FabioZTessitore** [comment]
passiamo a questo esercizio.
Caricalo in questa repo però

**Comment by Raffaelefrn** [comment]
In hellowolrd ?

2016-03-19 11:41 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
questa ...

**Comment by Raffaelefrn** [comment]
programma caricato

2016-03-30 17:03 GMT+02:00 Fabio Z Tessitore notifications@github.com:
