### ISSUE TITLE
SecondoGrado

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/ifelse#4]
Scrivi un programma che trovi le soluzioni a equazioni di secondo grado
nella forma ax^2+bx+c=0, con a, b e c interi.
Il programma dovrebbe tener conto dei casi particolari.

Per il calcolo della radice quadrata si puo' utilizzare la funzione `sqrt()`
della libreria matematica math

``` python
import math

... math.sqrt() ...
```

**Comment by Raffaelefrn** [comment]
programma caricato

2016-03-15 21:07 GMT+01:00 Fabio Z Tessitore notifications@github.com:
